### PR TITLE
Maintenance/web getting started

### PR DESCRIPTION
**Pull request by Jeroen-Veltmans**
Updates the web getting started guide.

- we recommend downloading the Web SDK through npm
- merged the multiple getting started guides
- reference the Open Video UI
- updated screenshots
- random tweaks
- redirect links for deleted pages

### CODE REVIEW

**Review by MattiasBuelens — APPROVED** [review]

**Comment by GillesMoris-THEO** [comment]
Something I got a question about today and that we might want to include: how to properly configure `libraryLocation` when installing through npm? Are you supposed to host and reference your node modules folder? I got this question of a customer using theo with npm and vite as a build tool.

**Comment by Jeroen-Veltmans** [comment]
As long as the `libraryLocation` points to a place that has the theoplayer folder it is good, so I would imagine that hosting the files from the `node_modules/theoplayer` directory and referencing them is a valid way to go. Not sure if there is a more optimal way to do it?

**Comment by MattiasBuelens** [comment]
It's tricky.

You probably don't want to put *your entire* `node_modules` folder on your app server. That folder contains more than your app's runtime dependencies: it also contains all your build dependencies (like the Vite bundler) and your development tools (like a web server). That's why you would want to use a bundler like Vite in the first place: to collect *only* your app's dependencies and combine them into one or more JavaScript bundles.

THEOplayer uses `libraryLocation` to load its web workers. However, Vite doesn't know that, because there's no `import from 'theoplayer/THEOplayer.transmux.js'` in our code. We don't want to load the web worker as part of the main app, we want to load it in a separate thread on the web worker. Modern bundlers have other ways to add additional assets to your bundle (like [`?worker`](https://vitejs.dev/guide/assets#importing-script-as-a-worker) or [`new URL()`](https://vitejs.dev/guide/assets#new-url-url-import-meta-url)), but there's no "standard" way of doing that which is supported by all bundlers and browsers. So for now, we're stuck with `libraryLocation`.

To get this to work in Vite, you should use [the `public` directory](https://vitejs.dev/guide/assets.html#the-public-directory):
1. Copy the contents of `node_modules/theoplayer` to `public/theoplayer/`,
2. Use `/theoplayer/` as your `libraryLocation`.

This is what we do in our React samples, see [`copy:theoplayer`](https://github.com/THEOplayer/samples-react-js/blob/9d9a72f7f7021dd788eee96abb868948201ef6f5/package.json#L12) and [`libraryLocation`](https://github.com/THEOplayer/samples-react-js/blob/9d9a72f7f7021dd788eee96abb868948201ef6f5/src/player/THEOplayerView.tsx#L23).

**Comment by GillesMoris-THEO** [comment]
Feels like something we should include as a note somewhere on our getting started, now that we're advising npm as the main approach for including THEOplayer.

**Comment by MattiasBuelens** [comment]
@GillesMoris-THEO Updated. 😉

**Review by GillesMoris-THEO — APPROVED** [review]

**Pull request merged**
